name : Java CI with Maven - Test and package
steps:
  - uses: actions/checkout@v5
  - uses: actions/setup-java@v5
    with:
      distribution: 'corretto'
      java-version: '21'
      cache: 'maven'
      cache-dependency-path: 'sub-project/pom.xml' # optional
  - name: Build with Maven
    run: mvn -B package --file pom.xml