name: Java CI with Maven - Test and package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'sub-project/pom.xml' # optionnel

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build and SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-') \
            -Dsonar.login=$SONAR_TOKEN
