name: Documentation

on:
  pull_request:
    types: [closed]

jobs:
  generate-doc:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '21'
      - run: mvn javadoc:javadoc
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/apidocs
